name: StaticAnalysis

on:
 push:
  paths:
  - 'src/**.cc'
  - 'src/**.h'
 pull_request:
  paths:
  - 'src/**.cc'
  - 'src/**.h'

defaults:
 run:
  shell: bash

jobs:

 StaticAnalysis:
  name:    Static analysis
  runs-on: ubuntu-latest
  steps:

  - name: Install
    run:  apt install cppcheck

  - name: cppcheck
    run:  cppcheck --std=c++17 src/
